FROM php:7.4-apache

COPY ./apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache2/start-apache /usr/local/bin
COPY ./src/adminer-4.8.1.php /var/www/public/index.php

RUN chmod +x /usr/local/bin/start-apache
RUN chown -R www-data:www-data /var/www

RUN a2enmod rewrite

CMD ["start-apache"]
